"use client";

import CalcRow from "@/components/common/CalcRow";
import InvoiceRow from "@/components/common/InvoiceRow";
import { calc, fmt } from "@/lib/calculations";
import type { ConsultationRecord, ToastMessage } from "@/types";

interface InvoiceViewProps {
  record: ConsultationRecord;
  onBack: () => void;
  showToast: (msg: string, type?: ToastMessage["type"]) => void;
}

export default function InvoiceView({ record, onBack, showToast }: InvoiceViewProps) {
  const r = record;
  const d = calc(Number(r.billAmount), Number(r.sharePct), Number(r.taxPct));

  const shareRecord = async () => {
    const text = `Dr. Consultation Record\nPatient: ${r.ptName} (${r.ptId})\nBill Date: ${r.billDate}\nBill Amount: ${fmt(r.billAmount)}\nMy Share (${r.sharePct}%): ${fmt(d.myShare)}\nTax (${r.taxPct}%): ${fmt(d.taxAmt)}\nNet Receivable: ${fmt(d.net)}\nPayment: ${r.paymentMode} | ${r.status}`;
    if (navigator.share) {
      await navigator.share({ title: "Consultation Record", text });
    } else {
      await navigator.clipboard.writeText(text);
      showToast("Copied to clipboard");
    }
  };

  const btnBase: React.CSSProperties = {
    border: "none",
    borderRadius: 10,
    padding: "12px 28px",
    cursor: "pointer",
    fontSize: 14,
    fontWeight: 600,
    transition: "all 0.2s",
    fontFamily: "'DM Sans', sans-serif",
  };

  return (
    <div id="print-area">
      <div
        style={{
          background: "#fff",
          borderRadius: 14,
          padding: "36px 40px",
          maxWidth: 620,
          boxShadow: "0 4px 20px rgba(15,76,92,0.1)",
        }}
      >
        {/* Header */}
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "flex-start",
          }}
        >
          <div>
            <div
              style={{
                fontFamily: "'Playfair Display', serif",
                fontSize: 22,
                color: "#0F2A2A",
                fontWeight: 700,
              }}
            >
              CONSULTATION RECEIPT
            </div>
            <div style={{ color: "#8AACAC", fontSize: 12, marginTop: 5 }}>
              Record ID: {r.id.toUpperCase()}
            </div>
          </div>
          <div style={{ fontSize: 40, opacity: 0.3 }}>⚕</div>
        </div>

        <hr style={{ border: "none", borderTop: "2px solid #E8F0F0", margin: "20px 0" }} />

        {/* Patient Info */}
        <div style={{ display: "flex", flexDirection: "column", gap: 2 }}>
          <InvoiceRow label="Patient Name"    val={r.ptName} />
          <InvoiceRow label="Patient ID"      val={r.ptId} />
          <InvoiceRow label="Bill Date"       val={r.billDate} />
          <InvoiceRow label="Payment Mode"    val={r.paymentMode} />
          <InvoiceRow label="Date of Receipt" val={r.receiptDate || "—"} />
          <InvoiceRow label="Status"          val={r.status} highlight />
        </div>

        <hr style={{ border: "none", borderTop: "2px solid #E8F0F0", margin: "20px 0" }} />

        {/* Calculations */}
        <div
          style={{
            background: "#F5FAFA",
            borderRadius: 10,
            padding: "18px 20px",
          }}
        >
          <CalcRow label="Bill Amount" val={fmt(r.billAmount)} />
          <CalcRow
            label={`Consultation Share (${r.sharePct}%)`}
            val={fmt(d.myShare)}
            highlight
          />
          <CalcRow
            label={`TDS / Tax (${r.taxPct}%)`}
            val={`− ${fmt(d.taxAmt)}`}
            red
          />
          <div style={{ borderBottom: "2px solid #D4EAEA", margin: "10px 0" }} />
          <CalcRow label="Final Net Receivable" val={fmt(d.net)} big />
        </div>

        {r.notes && (
          <div
            style={{
              background: "#FFF8EC",
              borderRadius: 8,
              padding: "12px 16px",
              fontSize: 13,
              color: "#7A6A2A",
              marginTop: 16,
            }}
          >
            Notes: {r.notes}
          </div>
        )}

        <hr style={{ border: "none", borderTop: "2px solid #E8F0F0", margin: "24px 0 0" }} />
        <div style={{ textAlign: "center", fontSize: 11, color: "#AACACA" }}>
          Generated by MedFinance · {new Date().toLocaleDateString("en-IN")}
        </div>

        {/* Actions */}
        <div style={{ display: "flex", gap: 12, marginTop: 24 }} className="no-print">
          <button
            className="btn-hover"
            onClick={() => window.print()}
            style={{
              ...btnBase,
              background: "linear-gradient(135deg, #0F4C5C, #1A7A5E)",
              color: "#fff",
            }}
          >
            🖨 Print Invoice
          </button>
          <button
            className="btn-hover"
            onClick={shareRecord}
            style={{
              ...btnBase,
              background: "#F0F7F7",
              color: "#0F4C5C",
              border: "1.5px solid #CCDEDE",
            }}
          >
            📤 Share
          </button>
          <button
            className="btn-hover"
            onClick={onBack}
            style={{
              ...btnBase,
              background: "#F0F7F7",
              color: "#0F4C5C",
              border: "1.5px solid #CCDEDE",
            }}
          >
            ← Back
          </button>
        </div>
      </div>
    </div>
  );
}
